---
title: "Relatório de prestação de contas"
author: "William Nilson de Amorim"
date: "24 de março de 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Título da tese**: Ciência de dados, poluição do ar e saúde

**Instituição de ensino**: Instituto de Matemática e Estatística da Universidade de São Paulo (IME-USP)

**Departamento**: Departamento de Estatística

**Orientador**: Prof. Dr. Antonio Carlos Pedroso de Lima

# Utilização dos recursos da taxa de bancada

Durante a vigência da bolsa, R$ 9.456,00 foi pago pela CNPq como taxa de bancada. Esse valor foi utilizado na compra dos seguintes itens:

- Passagens de ônibus de ida e volta (São Paulo - Curitiba) para apresentação de trabalho no Rday, Encontro Nacional de usuários do R, no dia 22 de maio de 2018. Empresas: Cometa (ida) e Grupo JCA. **Valor: R$ 141.80**.

- Passagem de volta de São Carlos para São Paulo após apresentação de minicurso no evento Semana de Estatística realizada pela UFSCAR e ICMC-USP, nos dias 23 a 25 de maio de 2018. Empresa: Grupo JCA. **Valor: R$ 65.81**.

- Notebook 2 em 1 Inspiron I13-5378-A40C Intel Core 7 I7 8GB 256GB SSD Full Hd 13.3" Touch W10 --- para realização de tarefas rotineiras relacionadas ao desenvolvimento da tese, como ajuste de análises mais simples, produção do texto, preparo de apresentações e relatórios etc. Este item foi doado ao Instituto de Matemática e Estatística da Universidade de São Paulo após finalização dos trabalhos. Essa compra foi realizada no [Submarino.com.](https://www.submarino.com.br). **Valor: R$ 4.019,98**.

- Servidor GA-H110M-S2V, Intel Core Core I7-7700K Kaby Lake LGA 1151 4.2Ghz 8MB Cache,, 32GB de RAM, GeForce GTX 1050 4GB, 256 SSD, 1TB HD --- para realização de tarefas específicas relacionadas ao desenvolvimento da tese, como ajuste de modelos mais complexos, que exigem maior poderio computacional. Esse servidor foi de imediato doado ao Instituto de Matemática e Estatística da Universidade de São Paulo, sendo que o acesso a ele pelo bolsista era realizado de forma remota. Essa compra foi realizda na [Pichau informática](https://www.pichau.com.br/). **Valor: R$ 4.813,08**

Valor total utilizado: R$ 9.040,67.

Valor a devolver: R$ 415.33.