---
title: "Ozônio e clima (2008-2013)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r, echo = FALSE}
library(tidyverse)

source("utils/utils-ozonio-regressao-linear.R")
source("utils/utils-ozone-models.R")
```

# Todo o período

## Dados

```{r}
df_salvo <- read_rds("../data/artaxo-salvo-geiger/data-asg.rds")
```

## Modelo linear

Modificando banco de dados para rodar o modelo e gerando formula.

```{r}
df_model <- df_salvo %>%
  filter(dv_o3 == 1) %>% 
  group_by(stationname) %>% 
  mutate(trend = 1:n()) %>% 
  ungroup() %>% 
  mutate(
    week = as.factor(week),
    dv_day_ = case_when(
      dayofweek %in% 1:5 & dv_yearendvacation == 1 ~ "week_vac",
      dayofweek == 0 & dv_yearendvacation == 1 ~ "sun_vac",
      dayofweek == 6 & dv_yearendvacation == 1 ~ "sat_vac",
      dayofweek == 0 & dv_yearendvacation == 0 ~ "sun_reg",
      dayofweek == 1 & dv_yearendvacation == 0 ~ "mon_reg",
      dayofweek == 2 & dv_yearendvacation == 0 ~ "tue_reg",
      dayofweek == 3 & dv_yearendvacation == 0 ~ "wed_reg",
      dayofweek == 4 & dv_yearendvacation == 0 ~ "thu_reg",
      dayofweek == 5 & dv_yearendvacation == 0 ~ "fri_reg",
      dayofweek == 6 & dv_yearendvacation == 0 ~ "sat_reg"
    ),
    dv_pp = case_when(
      pp == 0 ~ "_0_0",
      between(pp, 0, 5) ~ "_0_5",
      between(pp, 5, 20) ~ "_5_20",
      TRUE ~ "_20_max"
    )
  )

formula <- df_model %>%
  select(
    -stationname,
    -date, -o3_mass_conc, -dayofweek,
    -pp,
    -year, -month, -day, -dv_weekday_regular, -dv_yearendvacation, -dv_o3
  ) %>% 
  names() %>% 
  stringr::str_c(collapse = " + ") %>% 
  stringr::str_c("o3_mass_conc ~ ", .) %>%
  as.formula()

# Number of coefficients
ncol(model.matrix(formula, df_model))
```

Modelo linear 

```{r}
set.seed(5893524)

stations <- unique(df_model$stationname)
models <- map(stations, fit_linear_reg, df = df_model, formula = formula)
```

## Avaliando modelos

```{r}
# Share_gas coefficients
coef_table(models) %>% 
  select(Station, share_gas) %>% 
  mutate(signal = ifelse(share_gas < 0, "-", "+"))

# RMSE for each model
rmse_table(models)
```

# Tirando meses frios

## Dados

Modificando banco de dados para rodar o modelo e gerando formula.

```{r}
df_model_reduced <- df_salvo %>%
  filter(dv_o3 == 1, !month %in% 6:9) %>% 
  group_by(stationname) %>% 
  mutate(trend = 1:n()) %>% 
  ungroup() %>% 
  mutate(
    week = as.factor(week),
    dv_day_ = case_when(
      dayofweek %in% 1:5 & dv_yearendvacation == 1 ~ "week_vac",
      dayofweek == 0 & dv_yearendvacation == 1 ~ "sun_vac",
      dayofweek == 6 & dv_yearendvacation == 1 ~ "sat_vac",
      dayofweek == 0 & dv_yearendvacation == 0 ~ "sun_reg",
      dayofweek == 1 & dv_yearendvacation == 0 ~ "mon_reg",
      dayofweek == 2 & dv_yearendvacation == 0 ~ "tue_reg",
      dayofweek == 3 & dv_yearendvacation == 0 ~ "wed_reg",
      dayofweek == 4 & dv_yearendvacation == 0 ~ "thu_reg",
      dayofweek == 5 & dv_yearendvacation == 0 ~ "fri_reg",
      dayofweek == 6 & dv_yearendvacation == 0 ~ "sat_reg"
    ),
    dv_pp = case_when(
      pp == 0 ~ "_0_0",
      between(pp, 0, 5) ~ "_0_5",
      between(pp, 5, 20) ~ "_5_20",
      TRUE ~ "_20_max"
    )
  )

formula <- df_model_reduced %>%
  select(
    -stationname,
    -date, -o3_mass_conc, -dayofweek,
    -pp,
    -year, -month, -day, -dv_weekday_regular, -dv_yearendvacation, -dv_o3
  ) %>% 
  names() %>% 
  stringr::str_c(collapse = " + ") %>% 
  stringr::str_c("o3_mass_conc ~ ", .) %>%
  as.formula()

# Number of coefficients
ncol(model.matrix(formula, df_model_reduced))
```

Modelo linear 

```{r}
set.seed(5893524)

stations <- unique(df_model_reduced$stationname)
models_reduced <- map(stations, fit_linear_reg, df = df_model_reduced, formula = formula)
```

## Avaliando modelos

```{r}
# Share_gas coefficients
coef_table(models_reduced) %>% 
  select(Station, share_gas) %>% 
  mutate(signal = ifelse(share_gas < 0, "-", "+"))

# RMSE for each model
rmse_table(models)
```


# Criando tabelas

Saída latex para a tese.

```{r}
coef_all <- coef_table(models) %>% 
  select(Station, share_gas) 

coef_reduced <- coef_table(models_reduced) %>% 
  select(Station, share_gas_reduced = share_gas) 

inner_join(coef_all, coef_reduced, by = "Station") %>% 
  mutate(empty = "") %>% 
  xtable::xtable(auto = TRUE) %>% 
  print(include.rownames = FALSE)
```