---
title: "Ozônio - GAM (2008-2013)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r, echo = FALSE}
library(tidyverse)

source("scripts/utils-ozonio-gam.R")
source("scripts/utils-ozone-models.R")
```

# Todo o período

## Dados

Modificando banco de dados para rodar o modelo e gerando formula.

```{r}
df_model <- read_rds("data/df_salvo_2017.rds") %>% 
  mutate_at(
    vars(dayofweek, week, month, 
         dv_ti_0to199m_9am, dv_ti_200to499m_9am, dv_beltway_open),
    funs(as.factor)
  ) %>%
  mutate(pp_m = ifelse(pp_m == 0, 0, 1),
         pp_m = as.factor(pp_m),
         pp = ifelse(pp == 0, 0, 1),
         pp = as.factor(pp))

formula <- df_model %>%
  select(-dv_ti_0to199m, -dv_ti_200to499m,
         -date, -week, -dayofweek, -trend, -month,
         - o3_mass_conc, -stationname) %>%
  names() %>% 
  stringr::str_c(collapse = " + ") %>% 
  stringr::str_c("o3_mass_conc ~ s(trend) + ", .) %>%
  as.formula()
```

Modelo linear 

```{r}
set.seed(5893524)

stations <- unique(df_model$stationname)
models <- map(stations, 
              fit_gam, 
              df = df_model, 
              formula = formula,
              family = gaussian())

rmse_table(models)
coef_table(models)
```

Comparando modelos

```{r}
inner_join(rmse_bench, rmse_table(models), by = "Station")

stop("Não!")

models_bench <- models
rmse_bench <- rmse_table(models_bench) %>% 
  rename(RMSE_bench = RMSE)

```

```{r}
coef_table(models) %>% 
  select(Station, share_gas) %>% 
  mutate(signal = ifelse(share_gas < 0, "-", "+")) %>%
  count(signal)
```


# Tirando meses frios

## Dados

Modificando banco de dados para rodar o modelo e gerando formula.

```{r}
df_model <- read_rds("data/df_salvo_2017.rds") %>%
  filter(!month %in% 6:9) %>% 
  mutate_at(
    vars(dayofweek, week, month, 
         dv_ti_0to199m_9am, dv_ti_200to499m_9am, dv_beltway_open),
    funs(as.factor)
  ) %>%
  mutate(pp_m = ifelse(pp_m == 0, 0, 1),
         pp_m = as.factor(pp_m),
         pp = ifelse(pp == 0, 0, 1),
         pp = as.factor(pp))

formula <- df_model %>%
  select(-dv_ti_0to199m, -dv_ti_200to499m,
         -date, -week, -dayofweek, -trend,
         - o3_mass_conc, -stationname) %>%
  names() %>% 
  stringr::str_c(collapse = " + ") %>% 
  stringr::str_c("o3_mass_conc ~ ", .) %>%
  as.formula()
```

Modelo linear 

```{r}
set.seed(5893524)

stations <- unique(df_model$stationname)
models <- map(stations, fit_linear_reg, df = df_model, formula = formula)
```

Comparando modelos

```{r}
inner_join(rmse_bench, rmse_table(models), by = "Station")

stop("Não!")

models_bench <- models
rmse_bench <- rmse_table(models_bench) %>% 
  rename(RMSE_bench = RMSE)

```

```{r}
coef_table(models) %>% 
  select(Station, share_gas) %>% 
  mutate(signal = ifelse(share_gas < 0, "-", "+")) %>%
  count(signal)
```