---
title: "Ozônio e uso de combustível (2008-2013)"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r, echo = FALSE}
library(tidyverse)
```

## Problema

Investigar a relação entre ozõnio, tráfego e uso de combustível na cidade de São Paulo usando dados de 2008 a 2013.

## Dados {.smaller}

```{r, eval = FALSE, include=FALSE}
# Filtra a base original
readr::read_csv("../data/artaxo-salvo-geiger/dados_originais.csv") %>%
  dplyr::mutate(date = lubridate::ymd(stringr::str_c(year, month, day, sep = "-"))) %>% 
  dplyr::select(date, hour, dayofweek, dv_weekday_regular,
         siteid, 
         o3_mass_conc,
         congestion_city,
         congestion_region,
         share_gas) %>% 
  readr::write_rds(path = "data/df_O3_combustiveis_2008_2013.rds", compress = "gz")
```

Vamos utilizar a média diária de ozônio medido entre 12h e 17h, focando inicialmente na estação Dom Pedro II.

```{r, message=FALSE}
df_O3 <- readr::read_rds("data/df_O3_combustiveis_2008_2013.rds")

df_tarde_DPII <- df_O3 %>%
  dplyr::filter(siteid == 1, hour %in% 12:16) %>% 
  dplyr::group_by(date) %>%
  dplyr::summarise_at(.vars = vars(dayofweek, o3_mass_conc, congestion_city,
                                   congestion_region, share_gas),
                      .funs = funs(mean),
                      na.rm = TRUE) %>%  
  dplyr::ungroup()
```

## Dados {.smaller}

Vamos adicionar agora as médias no período da manhã (6h-10h). 

```{r}
medidas_manha <- df_O3 %>%
  dplyr::filter(siteid == 1, hour %in% 6:10) %>% 
  dplyr::group_by(date) %>%
  dplyr::summarise_at(.vars = vars(congestion_region, congestion_city,
                                   share_gas),
                      .funs = funs(mean),
                      na.rm = TRUE)  %>%
  rename(morning_congestion_city = congestion_city,
         morning_congestion_region = congestion_region,
         morning_share_gas = share_gas)

df_tarde_DPII <- df_tarde_DPII %>%  
  left_join(medidas_manha, by = "date")

```


## Ozônio ao longo da semana

```{r}
dias <- c("Domingo", "Segunda", "Terça", "Quarta", "Quinta", 
          "Sexta", "Sábado")

df_tarde_DPII %>% 
  group_by(dayofweek) %>% 
  summarise(o3_mass_conc = mean(o3_mass_conc, na.rm = TRUE)) %>% 
  mutate(dayofweek = as.factor(dayofweek),
         dayofweek = forcats::lvls_revalue(dayofweek, dias),
         dayofweek = forcats::lvls_reorder(dayofweek, c(1, 7, 6:2)),
         o3_mass_conc_lab = round(o3_mass_conc, 1),
         o3_mass_conc_lab = format(o3_mass_conc_lab, nsmall = 1)) %>% 
  ggplot() +
  geom_bar(aes(x = dayofweek, y = o3_mass_conc), 
           stat = "identity", fill = "royalblue") +
  geom_text(aes(x = dayofweek, y = 30, label = dayofweek), color = "white",
            fontface = 2) +
  geom_text(aes(x = dayofweek, y = o3_mass_conc - 3, label = o3_mass_conc_lab),
            color = "white") +
  coord_flip() +
    theme_bw() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  labs(y = expression(paste(O[3], " (", mu, "g/", m^3, ")")), 
       x = "Day of week")
```

## Trânsito local

```{r, echo = FALSE}
df_tarde_DPII %>% 
  dplyr::select(date, O3 = o3_mass_conc, 
                congestion_region,
                morning_congestion_region) %>% 
  tidyr::gather(serie, value, O3, 
                congestion_region, morning_congestion_region) %>% 
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  geom_smooth(se = FALSE) +
  facet_wrap(~serie, nrow = 3, scales = "free_y") +
  theme_bw() +
  labs(x = "Year", y = "Value")
```

```{r}
library(ggridges)

df_tarde_DPII %>% 
  dplyr::select(date, congestion_region, morning_congestion_region) %>% 
  tidyr::gather(serie, value, 
                congestion_region, morning_congestion_region) %>%
  mutate(month = lubridate::month(date),
         month = as.factor(month)) %>% 
ggplot(aes(x = value, y = month, fill = month)) + 
  geom_density_ridges(show.legend = FALSE) +
  facet_wrap(~serie, ncol = 2, scales = "free") +
  labs(y = "Month", x = "Km") +
  theme_bw()
```

```{r}
df_tarde_DPII %>% 
  dplyr::select(date, o3_mass_conc, congestion_region, 
                morning_congestion_region) %>% 
  tidyr::gather(serie, value, 
                congestion_region, morning_congestion_region) %>%
ggplot(aes(x = value, y = o3_mass_conc)) +
  geom_point() +
  facet_wrap(~serie) +
  theme_bw()
  
```


```{r}
df_tarde_DPII %>%
  group_by(dayofweek) %>% 
  summarise(congestion_region = mean(congestion_region, na.rm = TRUE),
            morning_congestion_region = 
              mean(morning_congestion_region, na.rm = TRUE)) %>% 
  mutate(dayofweek = as.factor(dayofweek),
         dayofweek = forcats::lvls_revalue(dayofweek, dias),
         dayofweek = forcats::lvls_reorder(dayofweek, c(1, 7, 6:2))) %>%
  gather(serie, value, -dayofweek) %>% 
  mutate(value_lab = round(value, 1),
         value_lab = format(value_lab, nsmall = 1)) %>% 
  ggplot() +
  geom_bar(aes(x = dayofweek, y = value), 
           stat = "identity", fill = "royalblue") +
  geom_text(aes(x = dayofweek, y = value - 3, label = value_lab),
            color = "white") +
  facet_wrap(~serie) +
  coord_flip() +
    theme_bw() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  labs(y = expression(paste(O[3], " (", mu, "g/", m^3, ")")), 
       x = "Day of week")

```


## Trânsito cidade

```{r, echo = FALSE}
df_tarde_DPII %>% 
  dplyr::select(date, O3 = o3_mass_conc, 
                congestion_city,
                morning_congestion_city) %>% 
  tidyr::gather(serie, value, O3, 
                congestion_city, morning_congestion_city) %>% 
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  geom_smooth(se = FALSE) +
  facet_wrap(~serie, nrow = 3, scales = "free_y") +
  theme_bw() +
  labs(x = "Year", y = "Value")
```


```{r}
library(ggridges)

df_tarde_DPII %>% 
  dplyr::select(date, congestion_city, morning_congestion_city) %>% 
  tidyr::gather(serie, value, 
                congestion_city, morning_congestion_city) %>%
  mutate(month = lubridate::month(date),
         month = as.factor(month)) %>% 
ggplot(aes(x = value, y = month, fill = month)) + 
  geom_density_ridges(show.legend = FALSE) +
  facet_wrap(~serie, ncol = 2, scales = "free") +
  labs(y = "Month", x = "Km") +
  theme_bw()
```

```{r}
df_tarde_DPII %>% 
  dplyr::select(date, o3_mass_conc, congestion_city, 
                morning_congestion_city) %>% 
  tidyr::gather(serie, value, 
                congestion_city, morning_congestion_city) %>%
ggplot(aes(x = value, y = o3_mass_conc)) +
  geom_point() +
  facet_wrap(~serie) +
  theme_bw()
  
```

